web:
  build: .
  volumes:
    - ".:/code"
  ports:
    - "8000:80"
  links:
    - blackfire
    - elasticsearch
    - mysql
  environment:
    - MYSQL_HOST=mysql

blackfire:
  image: blackfire/blackfire
  env_file: ./myapp/.env

elasticsearch:
  image: elasticsearch:1.7
  ports:
    - "9200:9200"
    - "9300:9300"

mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  env_file: ./myapp/.env