web:
  build: .
  volumes:
    - ".:/code"
  links:
    - elasticsearch
    - mysql
  environment:
    - ELASTICSEARCH_HOST=elasticsearch
    - MYSQL_HOST=mysql

blackfire:
  image: blackfire/blackfire
  env_file: ./myapp/.env

elasticsearch:
  image: elasticsearch:1.7
  ports:
    - "9200:9200"
    - "9300:9300"

phpfpm:
  build: php-fpm/
  links:
    - blackfire
    - elasticsearch
    - mysql
  volumes_from:
    - web

mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  env_file: ./myapp/.env

nginx:
  build: nginx/
  ports:
    - "8000:80"
  links:
    - phpfpm
  volumes_from:
    - web
  environment:
    APP_SERVER_NAME: symfony-boilerplate.dev
