# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    elastica.connection:
      host: "%elasticsearch_host%"
      port: "%elasticsearch_port%"

services:
    elastica.client:
        class: Elastica\Client
        arguments: ["%elastica.connection%"]

    elastica.search:
        class: Elastica\Search
        arguments: ["@elastica.client"]
